# Generated by Django 2.1 on 2020-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
